name: RubyGems.org Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
      - run: gem build slenips.gemspec
      - run: gem install ./slenips-*.gem
      - run: gem push ./slenips-*.gem
